### ISSUE TITLE
making it more generic

### ISSUE THREAD

**Issue by arabshapt** [yshalsager/calibre-with-kfx#3]
Hi, this is really great! I wanted to use your project as a base for normal calibre server with built in Kindle Previewer(in wine).
How could make it more generic? Similar to this one: https://hub.docker.com/r/linuxserver/calibre
With only difference, that it has Kindle Previewer in wine.

**Comment by yshalsager** [comment]
Hello,

Glad to hear it's useful for you!

Can you please elaborate your use case more? I haven't used the mentioned image, so no idea what are the limitations of my image compared to it.

Also, note that Kindle previewer will only work on a 64 bit system.

**Comment by arabshapt** [comment]
Thank you for your response:)
I have the following use case. I am running calibre server in docker container. Here is how my current yml looks like:
```
version: '3.3'
services:
    linuxserver:
        container_name: calibre
        ports:
            - '8080:8080'
            - '8081:8081'
        environment:
            - PUID=1026
            - PGID=100
            - TZ=Europe/Berlin
            - CUSTOM_USER=something
            - PASSWORD=something
        volumes:
            - '/volume1/calibre/data:/config'
        restart: always

        image: ghcr.io/linuxserver/calibre
```

I typically use calibre on my pc to convert epub to kfx, but I would like to run calibre on my home server and access it through web ui(it looks exactly the same as desktop app) and for that I need Kindle previewer in docker container. The problem is that the image that I am using is different from what you are using. It would be great to have this ghcr.io/linuxserver/calibre extended by Kindle Previewer in Wine.

**Comment by mgrimace** [comment]
I think my question is similar to the original poster, can this be used as a drop-in replacement for the 'regular' docker calibre? I also use ghcr.io/linuxserver/calibre image, similar to above. As in, can I still access calibre webui, etc. with your image? 

My current .yaml

```yaml
services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    env_file:
      - /opt/appdata/.id.env
      - /opt/appdata/.timezone.env
    volumes:
      - /mnt/media/media/books:/config #change before the ':'
      - /mnt/media/media/books/uploads:/uploads #change before the ':'
      - /mnt/media/media/books/plugins:/plugins #change before the ':'
    ports:
      - 8086:8080 #change before the ':' if necessary
      - 8087:8081 #change before the ':' if necessary
    restart: unless-stopped
    networks:
      - homelab
    security_opt:
      - apparmor:unconfined
```
and my use case is to manage my library via the calibre web-ui (IP:8086), auto-upload books, convert. Ideally, I'd like to convert books to KFX in the docker calibre container webui.
